---
name: zhihudaily
version: 2
...
cron:
    - description: cron 1
	  url: fetch_now.php
	  schedule: every 10 mins,offset 0, from 6:00 to 24:00
	  timezone: Beijing
      
    - description: cron 2
	  url: fetch_day.php
	  schedule: every day of month 00:00
	  timezone: Beijing
handle:
	- rewrite: if( path == "/rss.xml" ) goto "rss.php"
